# version: "3.8"
services:
  qemu:
    container_name: qemu
    image: qemux/qemu-docker
    environment:
      HOST_PORTS: "22"
      RAM_SIZE: "16G"
      CPU_CORES: "7"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "2222:22"
    volumes:
      # Use local file (skip download)
      # Replace `~/github/qemu-docker-ssh/` with actual location
      - ~/github/qemu-docker-ssh/storage:/storage
      - ~/github/qemu-docker-ssh/debian-12.5.0-amd64-netinst.iso:/storage/boot.iso
    stop_grace_period: 2m
    restart: on-failure
